"""
Deterministic confidence scoring for RunBookAI investigations.

Confidence is NOT generated by the LLM.

    Confidence = w1*Diversity + w2*EvidenceCount - w3*ContradictionPenalty
"""

from api.models import Evidence, EvidenceSource


# Positive weights sum to 1.0 so a clean run (3 sources, >=10 evidence,
# no contradiction) can reach 1.0. If you want a "never fully certain"
# ceiling instead, drop DIVERSITY_WEIGHT back to 0.4 (max becomes 0.9).
DIVERSITY_WEIGHT = 0.5
EVIDENCE_WEIGHT = 0.5
CONTRADICTION_WEIGHT = 0.4

MAX_SOURCES = 3       # metadata + logs + runbooks
EVIDENCE_TARGET = 10  # evidence count that saturates the evidence term


def calculate_confidence(
    evidence_sources: list[str],
    evidence_count: int,
    contradiction: bool,
) -> float:
    """
    Time O(n), Space O(k) — n = evidence items, k = unique sources.
    """
    unique_sources = set(evidence_sources)

    diversity_score = min(len(unique_sources) / MAX_SOURCES, 1.0)
    evidence_score = min(evidence_count / EVIDENCE_TARGET, 1.0)
    contradiction_penalty = 1.0 if contradiction else 0.0

    confidence = (
        DIVERSITY_WEIGHT * diversity_score
        + EVIDENCE_WEIGHT * evidence_score
        - CONTRADICTION_WEIGHT * contradiction_penalty
    )

    return round(max(0.0, min(confidence, 1.0)), 2)


def detect_contradiction(evidence: list[Evidence]) -> bool:
    """
    A real contradiction = the deployment STATUS is reported Healthy while the
    logs show errors. The mere presence of "running" (pod phase) is NOT enough,
    since a degraded service still has running/pending pods in its metadata.
    """
    metadata_text = " ".join(
        e.content.lower() for e in evidence if e.source == EvidenceSource.METADATA
    )
    logs_text = " ".join(
        e.content.lower() for e in evidence if e.source == EvidenceSource.LOGS
    )

    # Only "healthy" deployment status counts; if metadata also shows the
    # service is degraded/failed, it is NOT a contradiction — it's a real fault.
    metadata_healthy = '"status": "healthy"' in metadata_text or "'status': 'healthy'" in metadata_text
    metadata_degraded = "degraded" in metadata_text or "failed" in metadata_text or "crashloop" in metadata_text

    logs_have_errors = any(t in logs_text for t in ("error", "exception", "503"))

    return metadata_healthy and not metadata_degraded and logs_have_errors
def search_runbooks(query: str) -> str:
    return ""   # stubbed until Week 3 — empty so it isn't counted as evidence